/* Heartland - sales console.
   Built from heartland-sales-console.html by build_console.py. DO NOT EDIT THIS FILE.
   Edit the HTML, run the build, push. The HTML is the version you can open in a
   browser and click through; this is the version Webflow loads.

   On the page, all that is needed is:

     <style>html,body{margin:0;padding:0;background:#f9f9f7}
     @media(prefers-color-scheme:dark){html,body{background:#0d0d0d}}</style>
     <div id="hl-console-host"></div>
     <script src="https://cdn.jsdelivr.net/gh/daniellun-tov/heartland-scripts@main/heartland-console.js" defer><\/script>

   Everything else - every style, every element, every handler - is in here, sealed
   inside a shadow root so the marketing site's stylesheet cannot reach it. */
(function () {
  'use strict';

  var TPL = [
    "<style>",
    "  /* Scoped to the shadow root. :root never matches inside a shadow tree, so the",
    "     custom properties and the base typography both live on :host instead. */",
    "  :host {",
    "    display: block;",
    "    min-height: 100vh;",
    "    color-scheme: light;",
    "    --plane:#f9f9f7; --surface:#fcfcfb; --ink:#0b0b0b; --ink-2:#52514e; --ink-muted:#898781;",
    "    --rule:#e1e0d9; --ring:rgba(11,11,11,0.10);",
    "    --good:#0ca30c; --warning:#fab219; --serious:#ec835a; --critical:#d03b3b; --accent:#2a78d6;",
    "  }",
    "  @media (prefers-color-scheme: dark) {",
    "    :host {",
    "      color-scheme: dark;",
    "      --plane:#0d0d0d; --surface:#1a1a19; --ink:#fff; --ink-2:#c3c2b7; --ink-muted:#898781;",
    "      --rule:#2c2c2a; --ring:rgba(255,255,255,0.10); --accent:#3987e5;",
    "    }",
    "  }",
    "  * { box-sizing:border-box; }",
    "  :host { background:var(--plane); color:var(--ink);",
    "    font:15px/1.5 system-ui,-apple-system,\"Segoe UI\",sans-serif; }",
    "  .wrap { max-width:1280px; margin:0 auto; padding:20px 20px 72px; }",
    "  .card { background:var(--surface); border:1px solid var(--ring); border-radius:10px; }",
    "  h1 { font-size:1.2rem; margin:0; letter-spacing:-0.01em; }",
    "  h2 { font-size:.95rem; margin:0 0 10px; }",
    "  label { display:block; font-size:.8125rem; color:var(--ink-2); margin-bottom:5px; }",
    "  input, select, textarea { width:100%; padding:9px 11px; font:inherit; color:var(--ink);",
    "    background:var(--plane); border:1px solid var(--rule); border-radius:7px; }",
    "  input:focus, select:focus, textarea:focus { outline:2px solid var(--accent); outline-offset:1px; }",
    "  button { font:inherit; padding:8px 14px; border-radius:7px; cursor:pointer;",
    "    border:1px solid var(--ring); background:var(--surface); color:var(--ink); }",
    "  button.primary { background:var(--accent); border-color:transparent; color:#fff; }",
    "  button.danger { color:var(--critical); border-color:var(--critical); }",
    "  button[disabled] { opacity:.5; cursor:default; }",
    "  .row { display:flex; gap:10px; align-items:flex-end; flex-wrap:wrap; }",
    "  .err { color:var(--critical); font-size:.8125rem; min-height:1.2em; }",
    "  .ok { color:var(--good); font-size:.8125rem; min-height:1.2em; }",
    "  .muted { color:var(--ink-muted); }",
    "  .mono { font-variant-numeric:tabular-nums; }",
    "",
    "  /* login */",
    "  #login { max-width:400px; margin:10vh auto; padding:28px; }",
    "  #login p { color:var(--ink-2); font-size:.875rem; margin:0 0 18px; }",
    "",
    "  /* header */",
    "  header.top { display:flex; align-items:center; justify-content:space-between;",
    "    gap:16px; flex-wrap:wrap; margin-bottom:14px; }",
    "  .who { font-size:.8125rem; color:var(--ink-2); }",
    "  nav.tabs { display:flex; gap:4px; margin-bottom:16px; border-bottom:1px solid var(--rule); }",
    "  nav.tabs button { border:0; background:none; border-radius:0; padding:9px 14px;",
    "    color:var(--ink-2); border-bottom:2px solid transparent; }",
    "  nav.tabs button[aria-selected=\"true\"] { color:var(--ink); border-bottom-color:var(--accent); font-weight:600; }",
    "  .count { display:inline-block; margin-left:6px; font-size:.75rem; padding:0 6px;",
    "    border-radius:20px; background:var(--rule); color:var(--ink-2); }",
    "  .count.hot { background:var(--critical); color:#fff; }",
    "",
    "  /* today */",
    "  .group { margin-bottom:18px; padding:16px; }",
    "  .group h2 { display:flex; align-items:center; gap:8px; }",
    "  .group .why { font-size:.8125rem; color:var(--ink-2); margin:-4px 0 12px; }",
    "  .item { display:flex; gap:12px; align-items:baseline; justify-content:space-between;",
    "    padding:9px 0; border-bottom:1px solid var(--rule); flex-wrap:wrap; }",
    "  .item:last-child { border-bottom:0; }",
    "  .item .lead { font-weight:500; }",
    "  .item .meta { font-size:.8125rem; color:var(--ink-2); }",
    "  .none { color:var(--ink-muted); font-size:.875rem; padding:4px 0; }",
    "",
    "  /* filters + table */",
    "  .filters { display:flex; gap:10px; align-items:flex-end; flex-wrap:wrap; margin-bottom:12px; }",
    "  .filters .f { min-width:150px; }",
    "  .filters .f.grow { flex:1 1 220px; }",
    "  .tablewrap { overflow-x:auto; }",
    "  table { width:100%; border-collapse:collapse; font-size:.875rem; }",
    "  th,td { text-align:left; padding:9px 12px; border-bottom:1px solid var(--rule); vertical-align:top; }",
    "  th { font-size:.75rem; text-transform:uppercase; letter-spacing:.04em;",
    "    color:var(--ink-2); font-weight:600; white-space:nowrap; }",
    "  td.num, th.num { text-align:right; font-variant-numeric:tabular-nums; white-space:nowrap; }",
    "  tbody tr { cursor:pointer; }",
    "  tbody tr:hover { background:color-mix(in srgb, var(--accent) 7%, transparent); }",
    "  tbody tr:last-child td { border-bottom:0; }",
    "",
    "  /* status + pills */",
    "  .pill { display:inline-flex; align-items:center; gap:6px; white-space:nowrap; }",
    "  .dot { width:8px; height:8px; border-radius:50%; background:var(--ink-muted); flex:0 0 auto; }",
    "  .s-confirmed .dot { background:var(--good); }",
    "  .s-awaiting_payment .dot,.s-awaiting_clearance .dot,.s-held .dot { background:var(--warning); }",
    "  .s-payment_failed .dot { background:var(--serious); }",
    "  .s-cancelled .dot,.s-refunded .dot { background:var(--critical); }",
    "  .tag { font-size:.75rem; border:1px solid var(--rule); border-radius:20px;",
    "    padding:1px 8px; color:var(--ink-2); white-space:nowrap; }",
    "  .tag.crit { color:var(--critical); border-color:var(--critical); }",
    "  .tag.warn { color:var(--ink); border-color:var(--warning); }",
    "",
    "  /* drawer */",
    "  .scrim { position:fixed; inset:0; background:rgba(0,0,0,.35); display:none; }",
    "  .scrim.open { display:block; }",
    "  .drawer { position:fixed; top:0; right:0; bottom:0; width:min(560px,100%);",
    "    background:var(--surface); border-left:1px solid var(--ring); padding:22px;",
    "    overflow-y:auto; transform:translateX(100%); transition:transform .18s ease; }",
    "  .drawer.open { transform:none; }",
    "  .drawer header { display:flex; justify-content:space-between; align-items:flex-start; gap:12px; margin-bottom:4px; }",
    "  .dl { display:grid; grid-template-columns:auto 1fr; gap:6px 16px; font-size:.875rem; margin:10px 0 18px; }",
    "  .dl dt { color:var(--ink-2); }",
    "  .dl dd { margin:0; }",
    "  .sect { border-top:1px solid var(--rule); padding-top:16px; margin-top:16px; }",
    "  /* OTP link. Sales need to hand this to a buyer who has lost it, so the whole",
    "     row is one obvious copy affordance rather than a link buried in prose. */",
    "  .otprow { display:flex; gap:8px; align-items:center; margin:10px 0 8px; }",
    "  .otprow input { flex:1 1 auto; min-width:0; font-size:.75rem; padding:7px 9px;",
    "    border:1px solid var(--ring); border-radius:6px; background:var(--plane);",
    "    color:var(--ink-2); }",
    "  .otprow button { flex:0 0 auto; }",
    "  .otprow a { flex:0 0 auto; font-size:.8125rem; color:var(--ink-2); }",
    "  .stagebar { display:flex; gap:6px; flex-wrap:wrap; margin:10px 0 4px; }",
    "  .step { font-size:.75rem; padding:3px 9px; border-radius:20px;",
    "    border:1px solid var(--rule); color:var(--ink-muted); }",
    "  .step.done { color:var(--ink-2); border-color:var(--ink-2); }",
    "  .step.now { background:var(--accent); border-color:transparent; color:#fff; font-weight:600; }",
    "  .step.skip { opacity:.4; text-decoration:line-through; }",
    "  .hide { display:none !important; }",
    "  .spin { color:var(--ink-muted); font-size:.8125rem; }",
    "</style>",
    "</head>",
    "<body>",
    "",
    "<!-- \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500 login \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500 -->",
    "<div id=\"login\" class=\"card\">",
    "  <h1>Heartland sales console</h1>",
    "  <p>Sign in with your own account. Everything you change is recorded against your name.</p>",
    "  <div style=\"margin-bottom:12px\">",
    "    <label for=\"email\">Email</label>",
    "    <input id=\"email\" type=\"email\" autocomplete=\"username\" spellcheck=\"false\">",
    "  </div>",
    "  <div style=\"margin-bottom:16px\">",
    "    <label for=\"pw\">Password</label>",
    "    <input id=\"pw\" type=\"password\" autocomplete=\"current-password\">",
    "  </div>",
    "  <button class=\"primary\" id=\"signin\">Sign in</button>",
    "  <div class=\"err\" id=\"loginErr\" style=\"margin-top:12px\"></div>",
    "</div>",
    "",
    "<!-- \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500 app \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500 -->",
    "<div class=\"wrap hide\" id=\"app\">",
    "  <header class=\"top\">",
    "    <div>",
    "      <h1>Sales console</h1>",
    "      <div class=\"who\" id=\"who\">\u2014</div>",
    "    </div>",
    "    <div class=\"row\">",
    "      <button id=\"refresh\">Refresh</button>",
    "      <button id=\"csv\">Download CSV</button>",
    "      <button id=\"signout\">Sign out</button>",
    "    </div>",
    "  </header>",
    "",
    "  <nav class=\"tabs\">",
    "    <button id=\"tabToday\" aria-selected=\"true\">Today<span class=\"count\" id=\"todayCount\">0</span></button>",
    "    <button id=\"tabPipe\" aria-selected=\"false\">Pipeline<span class=\"count\" id=\"pipeCount\">0</span></button>",
    "  </nav>",
    "",
    "  <!-- Today -->",
    "  <section id=\"viewToday\"></section>",
    "",
    "  <!-- Pipeline -->",
    "  <section id=\"viewPipe\" class=\"hide\">",
    "    <div class=\"filters\">",
    "      <div class=\"f grow\">",
    "        <label for=\"q\">Search</label>",
    "        <input id=\"q\" type=\"text\" placeholder=\"Reservation number, name, email, phone, unit\">",
    "      </div>",
    "      <div class=\"f\"><label for=\"fstatus\">Payment status</label><select id=\"fstatus\"></select></div>",
    "      <div class=\"f\"><label for=\"fstage\">Deal stage</label><select id=\"fstage\"></select></div>",
    "      <div class=\"f\"><label for=\"fprop\">Property</label><select id=\"fprop\"></select></div>",
    "    </div>",
    "    <div class=\"card tablewrap\">",
    "      <table>",
    "        <thead><tr>",
    "          <th>Ref</th><th>Buyer</th><th>Property / unit</th><th>Payment</th><th>Deal stage</th>",
    "          <th>Deadline</th><th class=\"num\">Hold fee</th><th class=\"num\">Purchase price</th>",
    "        </tr></thead>",
    "        <tbody id=\"rows\"></tbody>",
    "      </table>",
    "      <div class=\"none\" id=\"empty\" style=\"padding:36px 20px; text-align:center\"></div>",
    "    </div>",
    "  </section>",
    "</div>",
    "",
    "<!-- \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500 drawer \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500 -->",
    "<div class=\"scrim\" id=\"scrim\"></div>",
    "<aside class=\"drawer\" id=\"drawer\" aria-hidden=\"true\"></aside>",
    ""
  ].join("\n");

  var BASE = "https://x7aj-untn-pq4t.n7e.xano.io/api:i0YhKPAV";
  var TOKEN_KEY = "hl_staff_token";
  var STAFF_KEY = "hl_staff_who";

  /* The console renders inside a shadow root. The host site's stylesheet defines its
     own .card, .row, .item and .tag, and CSS does not cross a shadow boundary - so
     this is what keeps a marketing-site class from reformatting a staff tool.
     ShadowRoot implements getElementById, so redefining this one helper is the whole
     change: every lookup below is unchanged. */
  /* Served from a file, not from a page, so the markup arrives as a string and is
     parsed into a template here. Everything downstream is unchanged: root is still
     a ShadowRoot and $ still calls getElementById on it. */
  var host = document.getElementById("hl-console-host");
  if (!host) {
    /* Loaded on a page that is not the console. Say so once and stop - throwing
       here would put a red error in the console of an ordinary marketing page. */
    console.warn("[hl-console] no #hl-console-host on this page - nothing to render.");
    return;
  }
  if (host.shadowRoot) {
    console.warn("[hl-console] already initialised - the script is on this page twice.");
    return;
  }
  var root = host.attachShadow({ mode: "open" });
  var tplEl = document.createElement("template");
  tplEl.innerHTML = TPL;
  root.appendChild(tplEl.content.cloneNode(true));

  var $ = function (id) { return root.getElementById(id); };
  var S = { data: null, staff: null, open: null, tab: "today", catalogue: {} };

  /* ---------- the deal machine, mirrored for the UI ----------
     The server is the authority; this exists so the console never
     offers a move the server will refuse. Keep the two in step. */
  var STAGES = ["reserve", "finance", "build", "move-in"];
  var SUBS = ["pre-qualify", "sign-otp", "pay-deposit", "transfer-attorneys", "bond-approval", "bond-approved"];
  var ROUTE = {
    bond: ["pre-qualify", "sign-otp", "pay-deposit", "transfer-attorneys", "bond-approval", "bond-approved"],
    cash: ["sign-otp", "pay-deposit", "transfer-attorneys"],
    undecided: ["sign-otp", "pay-deposit", "transfer-attorneys"]
  };
  var WINDOW_DAYS = {
    "pre-qualify": 7, "sign-otp": 7, "pay-deposit": 7,
    "transfer-attorneys": null, "bond-approval": 30, "bond-approved": null
  };

  /* ---------- storage ---------- */
  function token() { try { return sessionStorage.getItem(TOKEN_KEY) || ""; } catch (e) { return S.tok || ""; } }
  function setSession(t, staff) {
    S.tok = t; S.staff = staff;
    try {
      sessionStorage.setItem(TOKEN_KEY, t);
      sessionStorage.setItem(STAFF_KEY, JSON.stringify(staff));
    } catch (e) {}
  }
  function clearSession() {
    S.tok = ""; S.staff = null;
    try { sessionStorage.removeItem(TOKEN_KEY); sessionStorage.removeItem(STAFF_KEY); } catch (e) {}
  }
  function savedStaff() {
    try { return JSON.parse(sessionStorage.getItem(STAFF_KEY) || "null"); } catch (e) { return null; }
  }

  /* ---------- formatting ---------- */
  function rands(c) {
    return "R " + ((c || 0) / 100).toLocaleString("en-ZA", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  }
  function randsShort(c) { return "R " + Math.round((c || 0) / 100).toLocaleString("en-ZA"); }
  function day(ms) {
    if (!ms) { return "—"; }
    return new Date(ms).toLocaleDateString("en-ZA", { day: "2-digit", month: "short", year: "numeric" });
  }
  function when(ms) {
    if (!ms) { return "—"; }
    var d = new Date(ms);
    return d.toLocaleDateString("en-ZA", { day: "2-digit", month: "short" }) + " " +
           d.toLocaleTimeString("en-ZA", { hour: "2-digit", minute: "2-digit" });
  }
  function esc(s) {
    return String(s === null || s === undefined ? "" : s)
      .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  }
  function label(s) { return String(s || "").replace(/-/g, " ").replace(/_/g, " "); }
  function name(r) { return [r.first_name, r.last_name].filter(Boolean).join(" ") || r.email || "—"; }

  function deadline(r) {
    if (!r.deal_stage_due_at) { return '<span class="muted">—</span>'; }
    if (r.overdue) { return '<span class="tag crit">Overdue · ' + esc(day(r.deal_stage_due_at)) + "</span>"; }
    if (r.days_left !== null && r.days_left <= 3) {
      return '<span class="tag warn">' + r.days_left + "d left</span>";
    }
    return '<span class="mono">' + esc(day(r.deal_stage_due_at)) + "</span>";
  }

  /* ---------- api ---------- */
  function api(path, opts) {
    opts = opts || {};
    var headers = { "Content-Type": "application/json" };
    if (opts.auth !== false) { headers.Authorization = "Bearer " + token(); }
    return fetch(BASE + path, { method: opts.method || "GET", headers: headers, body: opts.body })
      .then(function (r) {
        return r.text().then(function (t) {
          var j = null;
          try { j = JSON.parse(t); } catch (e) {}
          if (!r.ok) {
            if (r.status === 401 && opts.auth !== false) { signOut("Your session expired. Sign in again."); }
            throw new Error((j && j.message) || ("Request failed (" + r.status + ")"));
          }
          return j;
        });
      });
  }

  /* ---------- load ---------- */
  function load() {
    var b = $("refresh");
    b.disabled = true; b.textContent = "Loading…";
    var qs = "?q=" + encodeURIComponent($("q").value) +
             "&status=" + encodeURIComponent($("fstatus").value) +
             "&deal_stage=" + encodeURIComponent($("fstage").value) +
             "&property=" + encodeURIComponent($("fprop").value);
    return api("/staff/reservations" + qs)
      .then(function (d) {
        S.data = d;
        render();
      })
      .catch(function (e) { $("who").textContent = "Could not load — " + e.message; })
      .then(function () { b.disabled = false; b.textContent = "Refresh"; });
  }

  /* ---------- render ---------- */
  function render() {
    var d = S.data;
    if (!d) { return; }
    $("who").textContent = d.staff.name + " · " + d.staff.role + " · " +
      d.matched + " of " + d.summary.total + " shown";
    fillFilters(d);
    renderToday(d);
    renderRows(d.items);
    $("pipeCount").textContent = d.matched;
    var urgent = d.summary.overdue + d.summary.needs_attention;
    var tc = $("todayCount");
    tc.textContent = urgent;
    tc.className = "count" + (urgent > 0 ? " hot" : "");
  }

  function fillFilters(d) {
    function fill(sel, opts, allLabel) {
      var keep = sel.value;
      sel.innerHTML = '<option value="">' + allLabel + "</option>" +
        opts.map(function (o) { return '<option value="' + esc(o.v) + '">' + esc(o.t) + "</option>"; }).join("");
      sel.value = keep;
    }
    fill($("fstatus"), Object.keys(d.summary.by_status).sort().map(function (k) {
      return { v: k, t: label(k) + " (" + d.summary.by_status[k] + ")" };
    }), "All");
    fill($("fstage"), STAGES.map(function (s) {
      return { v: s, t: label(s) + (d.summary.by_deal_stage[s] ? " (" + d.summary.by_deal_stage[s] + ")" : "") };
    }), "All");
    fill($("fprop"), (d.properties || []).map(function (p) {
      return { v: p.slug, t: p.name + (p.is_payfast_live ? "" : " — sandbox") };
    }), "All");
  }

  /* --- Today: what needs a human --- */
  function renderToday(d) {
    var all = d.items;
    var groups = [
      { key: "flagged", title: "Needs a decision", why: "Money arrived but the unit was lost, or someone left a note.",
        rows: all.filter(function (r) { return r.needs_attention; }) },
      { key: "overdue", title: "Deadline passed", why: "The countdown on the buyer's dashboard has run out.",
        rows: all.filter(function (r) { return r.overdue; }) },
      { key: "soon", title: "Due within three days", why: "Worth a call before it becomes the group above.",
        rows: all.filter(function (r) { return !r.overdue && r.days_left !== null && r.days_left <= 3; }) },
      { key: "clearing", title: "EFT still clearing", why: "Payfast has the payment as pending; the unit is held meanwhile.",
        rows: all.filter(function (r) { return r.status === "awaiting_clearance"; }) },
      { key: "nostage", title: "Paid, not yet in the pipeline", why: "Confirmed reservations nobody has moved into a deal stage.",
        rows: all.filter(function (r) { return r.status === "confirmed" && !r.deal_stage; }) }
    ];

    var html = groups.map(function (g) {
      var body = g.rows.length
        ? g.rows.map(function (r) {
            return '<div class="item" data-uuid="' + esc(r.uuid) + '">' +
              '<div><div class="lead">' + esc(name(r)) + "</div>" +
              '<div class="meta">' + esc(r.property_name) + " · " + esc(r.unit_name) +
              (r.deal_sub_stage ? " · " + esc(label(r.deal_sub_stage)) : "") + "</div></div>" +
              "<div>" + (g.key === "flagged"
                ? '<span class="tag crit">' + esc((r.admin_notes || "").slice(0, 60)) + "</span>"
                : deadline(r)) + "</div></div>";
          }).join("")
        : '<div class="none">Nothing here.</div>';
      return '<div class="card group"><h2>' + esc(g.title) +
        '<span class="count' + (g.rows.length && (g.key === "flagged" || g.key === "overdue") ? " hot" : "") + '">' +
        g.rows.length + "</span></h2>" +
        '<div class="why">' + esc(g.why) + "</div>" + body + "</div>";
    }).join("");

    $("viewToday").innerHTML = html;
    [].forEach.call($("viewToday").querySelectorAll(".item"), function (el) {
      el.style.cursor = "pointer";
      el.addEventListener("click", function () { openDrawer(el.getAttribute("data-uuid")); });
    });
  }

  /* --- Pipeline table --- */
  function renderRows(items) {
    var tb = $("rows"), em = $("empty");
    if (!items.length) {
      tb.innerHTML = "";
      em.classList.remove("hide");
      em.innerHTML = S.data.summary.total === 0
        ? "<strong>No reservations yet.</strong> The front end still writes to the old flow, so nothing has come through this one."
        : "Nothing matches those filters.";
      return;
    }
    em.classList.add("hide");
    tb.innerHTML = items.map(function (r) {
      return '<tr data-uuid="' + esc(r.uuid) + '">' +
        /* THE RESERVATION NUMBER LEADS THE ROW. It is the handle a buyer quotes on the
           phone and the one the OTP carries, so scanning for it must not mean reading a
           name first. A deal created before generate_reference existed has none - shown
           as a dash rather than blank, so the column reads as empty rather than broken. */
        '<td><span class="mono">' + esc(r.reference || "\u2014") + "</span></td>" +
        "<td><div>" + esc(name(r)) + "</div><div class=\"muted\">" + esc(r.email || "") + "</div></td>" +
        "<td>" + esc(r.property_name) + '<div class="muted">' + esc(r.unit_name) + "</div></td>" +
        '<td><span class="pill s-' + esc(r.status) + '"><span class="dot"></span>' + esc(label(r.status)) + "</span></td>" +
        "<td>" + (r.deal_stage ? esc(label(r.deal_stage)) +
            '<div class="muted">' + esc(label(r.deal_sub_stage || "")) + "</div>"
          : '<span class="muted">not started</span>') + "</td>" +
        "<td>" + deadline(r) + "</td>" +
        '<td class="num">' + esc(rands(r.reservation_fee_cents)) + "</td>" +
        '<td class="num">' + esc(rands(r.total_cents)) + "</td>" +
        "</tr>";
    }).join("");
    [].forEach.call(tb.querySelectorAll("tr"), function (tr) {
      tr.addEventListener("click", function () { openDrawer(tr.getAttribute("data-uuid")); });
    });
  }

  /* ---------- drawer ---------- */
  function find(uuid) {
    return (S.data.items || []).filter(function (r) { return r.uuid === uuid; })[0];
  }

  /* Only the steps this buyer's route actually walks, because that is exactly what
     the buyer sees on their own dashboard. Showing a cash buyer the bond steps -
     even greyed out - invites sales to discuss a step that will never arrive. */
  function stageBar(r) {
    var allowed = ROUTE[r.payer_route] || ROUTE.undecided;
    var idx = allowed.indexOf(r.deal_sub_stage);
    var bar = allowed.map(function (s, i) {
      var cls = "step";
      if (s === r.deal_sub_stage) { cls += " now"; }
      else if (idx > -1 && i < idx) { cls += " done"; }
      return '<span class="' + cls + '">' + esc(label(s)) + "</span>";
    }).join("");
    var hidden = SUBS.filter(function (s) { return allowed.indexOf(s) === -1; });
    if (hidden.length) {
      bar += '<span class="muted" style="font-size:.75rem;align-self:center">' +
             esc(label(r.payer_route || "undecided")) + " route — " +
             esc(hidden.map(label).join(", ")) + " never apply</span>";
    }
    return bar;
  }

  function stageOptions(r) {
    var allowed = ROUTE[r.payer_route] || ROUTE.undecided;
    if (!r.deal_sub_stage) { return allowed.slice(0, 1).concat(allowed.slice(1)); }
    var i = allowed.indexOf(r.deal_sub_stage);
    if (i === -1) { return allowed; }
    return allowed.filter(function (s, j) { return j !== i && j <= i + 1; });
  }

  function openDrawer(uuid) {
    var r = find(uuid);
    if (!r) { return; }
    S.open = uuid;

    var canStage = (r.status === "confirmed" || r.status === "awaiting_clearance");
    var opts = canStage ? stageOptions(r) : [];
    var pct = r.payer_route === "cash" ? r.deposit_cash_pct : r.deposit_bond_pct;
    var estDeposit = (pct && r.total_cents) ? Math.round(r.total_cents * pct / 100) : null;

    $("drawer").innerHTML =
      "<header><div><h1>" + esc(name(r)) + "</h1>" +
        '<div class="muted">' + esc(r.property_name) + " · " + esc(r.unit_name) +
          (r.reference ? ' · <span class="mono">' + esc(r.reference) + "</span>" : "") + "</div></div>" +
        '<button id="close">Close</button></header>' +

      '<dl class="dl">' +
        "<dt>Email</dt><dd>" + esc(r.email || "—") + "</dd>" +
        "<dt>Phone</dt><dd>" + esc(r.phone || "—") + "</dd>" +
        "<dt>Route</dt><dd>" + esc(label(r.payer_route)) + "</dd>" +
        "<dt>Payment</dt><dd>" + esc(label(r.status)) +
          (r.pf_payment_id ? ' <span class="muted mono">' + esc(r.pf_payment_id) + "</span>" : "") + "</dd>" +
        "<dt>Confirmed</dt><dd>" + esc(when(r.confirmed_at)) + "</dd>" +
        "<dt>Portal member</dt><dd>" + (r.has_member ? "yes" : '<span class="muted">not provisioned</span>') + "</dd>" +
      "</dl>" +

      /* The Offer to Purchase link. Built by Xano when the buyer confirms their
         details, then frozen - see the OTP LOCK block in update_reservation. Sales
         asked for it here so they can resend it to a buyer without going near the
         database. Read-only on purpose: this is a record of what was issued, and
         editing the query string by hand would change figures on a signed document. */
      '<div class="sect"><h2>Offer to Purchase</h2>' +
        (r.otp_url
          ? '<div class="otprow">' +
              '<input id="otpUrl" class="mono" readonly value="' + esc(r.otp_url) + '">' +
              '<button id="otpCopy">Copy link</button>' +
              '<a href="' + esc(r.otp_url) + '" target="_blank" rel="noopener">Open</a>' +
            "</div>" +
            '<div class="muted" style="font-size:.8125rem">Built when the buyer confirmed their details, and frozen from that point. Send this if they need it again.</div>'
          : '<div class="muted" style="font-size:.8125rem">No OTP link yet. It is built when the buyer confirms their details, and only for a route that has a template &mdash; Sanford has no cash template today.</div>') +
      "</div>" +

      '<div class="sect"><h2>Money</h2><dl class="dl">' +
        "<dt>Hold fee paid</dt><dd>" + esc(rands(r.reservation_fee_cents)) + "</dd>" +
        "<dt>Purchase price</dt><dd>" + esc(rands(r.total_cents)) +
          (r.addon_count ? ' <span class="muted">incl. ' + r.addon_count + " add-on" + (r.addon_count > 1 ? "s" : "") + "</span>" : "") + "</dd>" +
        "<dt>Purchase deposit</dt><dd>" +
          (r.purchase_deposit_cents !== null && r.purchase_deposit_cents !== undefined
            ? esc(rands(r.purchase_deposit_cents))
            : (estDeposit !== null
                ? '<span class="muted">not set — ' + esc(pct) + "% would be " + esc(randsShort(estDeposit)) + "</span>"
                : '<span class="muted">not set</span>')) + "</dd>" +
      "</dl>" +
      (r.addon_count
        ? '<div class="muted" style="font-size:.8125rem">' +
            r.addons.map(function (a) { return esc(a.name) + " · " + esc(rands(a.price_cents)); }).join("<br>") +
          "</div>"
        : "") +
      "</div>" +

      '<div class="sect"><h2>Deal stage</h2>' +
        (canStage
          ? '<div class="stagebar">' + stageBar(r) + "</div>" +
            '<div class="muted" style="font-size:.8125rem;margin-bottom:12px">' +
              (r.deal_stage_due_at
                ? (r.overdue ? "Deadline passed " : "Due ") + esc(day(r.deal_stage_due_at))
                : "No countdown on this step.") +
              (r.deal_stage_changed_at ? " · last moved " + esc(when(r.deal_stage_changed_at)) : "") +
            "</div>" +
            (opts.length
              ? '<div style="margin-bottom:10px"><label for="mvSub">Move to</label>' +
                '<select id="mvSub">' + opts.map(function (s) {
                  var w = WINDOW_DAYS[s];
                  return '<option value="' + esc(s) + '">' + esc(label(s)) +
                    (w ? " — " + w + " day window" : " — no countdown") + "</option>";
                }).join("") + "</select></div>" +
                '<div style="margin-bottom:10px"><label for="mvDue">Deadline override <span class="muted">(optional)</span></label>' +
                '<input id="mvDue" type="date"></div>' +
                '<div style="margin-bottom:12px"><label for="mvWhy">Reason</label>' +
                '<input id="mvWhy" type="text" placeholder="What happened"></div>' +
                '<button class="primary" id="mvGo">Move deal</button>' +
                '<div class="err" id="mvErr" style="margin-top:10px"></div>' +
                '<div class="ok" id="mvOk"></div>'
              : '<div class="none">Nothing further to move to on this route.</div>')
          : '<div class="none">A deal stage starts once the hold fee is paid. This reservation is ' +
            esc(label(r.status)) + ".</div>") +
      "</div>" +

      (r.admin_notes
        ? '<div class="sect"><h2>Note</h2><div style="color:var(--critical)">' + esc(r.admin_notes) + "</div></div>"
        : "") +

      (canStage
        ? '<div class="sect"><h2>Deadline</h2>' +
            '<div class="muted" style="font-size:.8125rem;margin-bottom:10px">Changes the countdown on this buyer\'s dashboard without moving their deal.</div>' +
            '<div style="margin-bottom:10px"><label for="dlDue">New deadline</label>' +
            '<input id="dlDue" type="date"></div>' +
            '<div style="margin-bottom:10px"><label style="display:flex;gap:8px;align-items:center;font-size:.8125rem">' +
              '<input id="dlClear" type="checkbox" style="width:auto"> Remove the deadline instead (for a step with no countdown)</label></div>' +
            '<div style="margin-bottom:12px"><label for="dlWhy">Reason</label>' +
            '<input id="dlWhy" type="text" placeholder="Why this buyer gets a different date"></div>' +
            '<button id="dlGo">Save deadline</button>' +
            '<div class="err" id="dlErr" style="margin-top:10px"></div><div class="ok" id="dlOk"></div>' +
          '</div>'
        : '') +

      '<div class="sect"><h2>Add-ons</h2>' +
        '<div class="muted" style="font-size:.8125rem;margin-bottom:10px">' +
          (canStage
            ? 'This changes the purchase price on a deal that may already be signed. The before and after are recorded against your name so an addendum can be written from it.'
            : 'Priced through the same rules engine the buyer uses.') +
        '</div>' +
        '<div id="addonBox"><div class="spin">Loading the catalogue\u2026</div></div>' +
        '<div id="addonFoot" class="hide">' +
          '<div class="muted" style="font-size:.8125rem;margin:10px 0">Add-ons subtotal, estimated: <span class="mono" id="addonEst">\u2014</span>' +
            '<br>The server reprices on save \u2014 bundles, dependencies and either/or groups can change this.</div>' +
          '<div style="margin-bottom:12px"><label for="adWhy">Reason</label>' +
          '<input id="adWhy" type="text" placeholder="What the buyer asked for"></div>' +
          '<button class="primary" id="adGo">Save add-ons</button>' +
          '<div class="err" id="adErr" style="margin-top:10px"></div><div class="ok" id="adOk"></div>' +
        '</div>' +
      '</div>' +

      '<div class="sect"><h2>Upgrades</h2>' +
        '<div class="muted" style="font-size:.8125rem;margin-bottom:10px">' +
          'Agreed with the buyer AFTER they reserved. These are kept out of the purchase price above &mdash; that is the figure the Offer to Purchase was signed at &mdash; and shown on their order summary as a separate total.' +
        '</div>' +
        '<div id="upBox"><div class="spin">Loading upgrades\u2026</div></div>' +
      '</div>' +

      '<div class="sect"><h2>Documents</h2>' +
        '<div class="muted" style="font-size:.8125rem;margin-bottom:10px">' +
          'Signed copies the buyer can download from their portal. Links must be https.' +
        '</div>' +
        '<div id="docBox"><div class="spin">Loading documents\u2026</div></div>' +
      '</div>' +

      /* WHAT THE BUYER SEES - THE ACTUAL PAGE, in a new tab. This was a panel of counts
         for about an hour, and a panel of counts is a second implementation of the
         portal: the first time it disagreed with the real page, the console would have
         been confidently wrong about what a buyer was looking at. The portal draws
         itself, with this buyer's data, through /staff/reservations/{uuid}/portal-view -
         one reader, no drift.

         A NEW TAB rather than an iframe, because the portal is a full page with its own
         navbar, tabs and theme, and because a salesperson wants to keep the deal open
         beside it.

         THE STAFF TOKEN GOES THROUGH localStorage, NEVER THE URL. A one-time note
         addressed to this reservation, good for sixty seconds, which the portal consumes
         and deletes. A token in a query string would live in history, in logs and in
         every referrer that page emits.

         Opening it is audited with your name - which is why it is a button and not
         something the drawer does on its own. */
      '<div class="sect"><h2>What the buyer sees</h2>' +
        '<div class="muted" style="font-size:.8125rem;margin-bottom:10px">' +
          'Opens their dashboard in a new tab, exactly as they see it. Read-only \u2014 the ' +
          'signing and pre-qualification links are disabled \u2014 and recorded against your name.' +
        '</div>' +
        '<div id="pvBox">' +
          (r.has_member
            ? '<button id="pvGo">Open the buyer\u2019s dashboard</button>'
            : '<div class="none">No member yet. A portal appears once the reservation fee is ' +
              'paid and the member is provisioned.</div>') +
        '</div>' +
      '</div>' +

      /* END THE DEAL. Last in the drawer because it is the only irreversible thing here. */
      (canStage && r.status !== "cancelled"
        ? '<div class="sect"><h2>End this deal</h2>' +
            '<div class="muted" style="font-size:.8125rem;margin-bottom:10px">' +
              'Releases the home in Xano and tells the buyer, in their portal, that the reservation is no longer active. ' +
              'Nothing is deleted \u2014 the record, the money and the documents stay. ' +
              'The Reserved toggle in the Webflow Units collection is <strong>not</strong> cleared; do that by hand.' +
            '</div>' +
            '<div style="margin-bottom:10px"><label for="cxWhy">Reason</label>' +
            '<input id="cxWhy" type="text" placeholder="The buyer reads this \u2014 write it for them"></div>' +
            (r.status === "confirmed"
              ? '<div style="margin-bottom:12px"><label style="display:flex;gap:8px;align-items:flex-start;font-size:.8125rem">' +
                  '<input id="cxPaid" type="checkbox" style="width:auto;margin-top:3px"> ' +
                  'This buyer has paid the hold fee. I am ending the deal anyway.</label></div>'
              : '') +
            '<button id="cxGo">Cancel this reservation</button>' +
            '<div class="err" id="cxErr" style="margin-top:10px"></div><div class="ok" id="cxOk"></div>' +
          '</div>'
        : (r.status === "cancelled"
            /* The reason is NOT read from the list row - list_reservations does not send
               cancel_reason, and printing a fallback here would put "no reason was
               recorded" on a deal that has one. The buyer's own view carries it. */
            ? '<div class="sect"><h2>Cancelled</h2><div class="muted" style="font-size:.8125rem">' +
              'This reservation has been ended and the home released. The reason the buyer reads is in ' +
              '\u201cWhat the buyer sees\u201d above.</div></div>'
            : '')) +

      '<div class="sect"><h2>Not editable here yet</h2>' +
        '<div class="muted" style="font-size:.8125rem">Recording a purchase-deposit payment. The columns exist; nothing writes them yet.</div></div>';

    $("scrim").classList.add("open");
    $("drawer").classList.add("open");
    $("drawer").setAttribute("aria-hidden", "false");

    $("close").addEventListener("click", closeDrawer);

    /* Copy. navigator.clipboard is the real path - the page is https and this runs
       from a click, so both of its preconditions hold. execCommand is the fallback
       for a browser that refuses. Neither is allowed to throw into the drawer, and
       the button says what happened rather than failing silently. */
    var otpCopy = $("otpCopy");
    if (otpCopy) {
      otpCopy.addEventListener("click", function () {
        var inp = $("otpUrl");
        if (!inp) { return; }
        var settle = function (ok) {
          otpCopy.textContent = ok ? "Copied" : "Select and press Ctrl+C";
          setTimeout(function () { otpCopy.textContent = "Copy link"; }, 2000);
        };
        try { inp.select(); inp.setSelectionRange(0, 99999); } catch (e) {}
        if (navigator.clipboard && navigator.clipboard.writeText) {
          navigator.clipboard.writeText(inp.value).then(
            function () { settle(true); },
            function () { settle(false); }
          );
          return;
        }
        var ok = false;
        try { ok = document.execCommand("copy"); } catch (e) { ok = false; }
        settle(ok);
      });
    }
    var go = $("mvGo");
    if (go) { go.addEventListener("click", function () { moveStage(r); }); }

    var dlGo = $("dlGo");
    if (dlGo) { dlGo.addEventListener("click", function () { saveDeadline(r); }); }

    var adGo = $("adGo");
    if (adGo) { adGo.addEventListener("click", function () { saveAddons(r); }); }

    var dlClear = $("dlClear");
    if (dlClear) {
      dlClear.addEventListener("change", function () {
        $("dlDue").disabled = dlClear.checked;
      });
    }

    var pvGo = $("pvGo");
    if (pvGo) { pvGo.addEventListener("click", function () { openBuyerView(r); }); }

    var cxGo = $("cxGo");
    if (cxGo) { cxGo.addEventListener("click", function () { cancelDeal(r); }); }

    loadCatalogue(r);
    loadUpgrades(r);
    loadDocuments(r);
  }

  /* ---------- the buyer's view ---------- */

  var PREVIEW_HANDOFF = "hl_preview_handoff";

  /* The handoff, and the whole security argument for it, is written up beside the
     panel above. Written immediately before the tab is opened so its sixty-second
     window starts as late as possible. */
  function openBuyerView(r) {
    var box = $("pvBox");
    var tok = token();
    if (!tok) {
      if (box) { box.innerHTML = '<div class="err">Your session has expired. Sign in again.</div>'; }
      return;
    }

    try {
      localStorage.setItem(PREVIEW_HANDOFF, JSON.stringify({
        t: tok, uuid: r.uuid, at: Date.now()
      }));
    } catch (e) {
      /* Private browsing, or storage blocked. Say so rather than opening a tab that
         will ask them to sign in with no explanation. */
      if (box) {
        box.innerHTML = '<div class="err">This browser will not let the console hand your ' +
          'session to another tab, so the preview cannot open. Storage is blocked \u2014 ' +
          'usually a private window or a strict privacy setting.</div>';
      }
      return;
    }

    /* NOT rel=noopener. The clone of sessionStorage into the new tab is the fallback
       the preview uses on a refresh, and severing the opener relationship is what
       stops some browsers making it. Both pages are ours and same-origin, so there is
       nothing here for noopener to protect against. */
    var win = window.open("/portal?preview=" + encodeURIComponent(r.uuid), "_blank");
    if (!win) {
      if (box) {
        box.innerHTML = '<div class="err">Your browser blocked the new tab. Allow pop-ups ' +
          'for this site and try again.</div>';
      }
      return;
    }
    if (box) {
      box.innerHTML = '<div class="ok">Opened in a new tab.</div>' +
        '<button id="pvGo">Open again</button>';
      var again = $("pvGo");
      if (again) { again.addEventListener("click", function () { openBuyerView(r); }); }
    }
  }

  /* ---------- cancel ---------- */
  function cancelDeal(r) {
    var why = ($("cxWhy").value || "").trim();
    var paid = $("cxPaid");
    var go = $("cxGo");

    if (why.length < 3) {
      $("cxErr").textContent = "Give a reason \u2014 the buyer reads it in their portal.";
      return;
    }
    if (!window.confirm("End " + (r.reference || "this reservation") + " for " + name(r) +
                        "?\n\nThe home is released and their portal will say the reservation is no longer active.")) {
      return;
    }

    go.disabled = true;
    $("cxErr").textContent = "";
    $("cxOk").textContent = "Cancelling\u2026";

    var body = { reason: why };
    if (paid && paid.checked) { body.confirm_paid = true; }

    api("/staff/reservations/" + encodeURIComponent(r.uuid) + "/cancel",
        { method: "POST", body: JSON.stringify(body) })
      .then(function (res) {
        $("cxOk").textContent = "Cancelled. " + (res.next_step || "");
        return load();
      })
      .then(function () { if (S.open) { openDrawer(S.open); } })
      .catch(function (e) { $("cxOk").textContent = ""; $("cxErr").textContent = e.message; })
      .then(function () { go.disabled = false; });
  }

  /* ---------- add-on editor ----------
     The catalogue comes from the same public endpoint the buyer's own page uses, so
     sales can never offer an add-on the buyer could not have chosen. Prices are shown
     for orientation only - they are never sent, and the server prices from its cache. */
  function loadCatalogue(r) {
    var box = $("addonBox");
    if (!box) { return; }

    var cached = S.catalogue[r.property_slug];
    if (cached) { renderAddonEditor(r, cached); return; }

    api("/public/addons?property=" + encodeURIComponent(r.property_slug), { auth: false })
      .then(function (d) {
        S.catalogue[r.property_slug] = d;
        if (S.open === r.uuid) { renderAddonEditor(r, d); }
      })
      .catch(function (e) {
        if (S.open === r.uuid) {
          box.innerHTML = '<div class="err">Could not load the catalogue \u2014 ' + esc(e.message) + "</div>";
        }
      });
  }

  function renderAddonEditor(r, cat) {
    var box = $("addonBox");
    if (!box) { return; }

    var chosen = {};
    (r.addons || []).forEach(function (a) { chosen[a.slug] = true; });

    var sections = (cat && cat.sections) || [];
    if (!sections.length) {
      box.innerHTML = '<div class="none">No add-ons are tagged to this property.</div>';
      return;
    }

    var html = sections.map(function (sec) {
      var rows = (sec.items || []).map(function (it) {
        var isOn = !!chosen[it.slug];
        // A sold-out add-on stays selectable only if this buyer already has it -
        // otherwise sales could re-add something there is no longer stock of.
        var blocked = it.sold_out && !isOn;
        var kind = it.radio_group ? "radio" : "checkbox";
        var nm = it.radio_group ? ' name="adgrp-' + esc(it.radio_group) + '"' : "";
        return '<label style="display:flex;gap:8px;align-items:baseline;padding:5px 0' +
          (blocked ? ";opacity:.45" : "") + '">' +
          '<input type="' + kind + '"' + nm + ' class="adopt" value="' + esc(it.slug) + '"' +
            ' data-cents="' + (it.price_cents || 0) + '"' +
            (it.radio_group ? ' data-group="' + esc(it.radio_group) + '"' : "") +
            (isOn ? " checked" : "") + (blocked ? " disabled" : "") +
            ' style="width:auto;margin-top:3px">' +
          "<span>" + esc(it.display_name) +
            ' <span class="muted mono">' + esc(it.price_display || rands(it.price_cents)) + "</span>" +
            (blocked ? ' <span class="tag">sold out</span>' : "") +
            (it.radio_group ? ' <span class="muted" style="font-size:.75rem">one of this group only</span>' : "") +
          "</span></label>";
      }).join("");

      var clearRow = "";
      var grp = (sec.items || []).filter(function (i) { return i.radio_group; })[0];
      if (grp) {
        clearRow = '<label style="display:flex;gap:8px;align-items:baseline;padding:5px 0">' +
          '<input type="radio" name="adgrp-' + esc(grp.radio_group) + '" class="adopt" value=""' +
          ' data-cents="0" data-group="' + esc(grp.radio_group) + '" style="width:auto;margin-top:3px">' +
          '<span class="muted">None from this group</span></label>';
      }

      return '<div style="margin-bottom:14px"><div style="font-size:.75rem;text-transform:uppercase;' +
        'letter-spacing:.04em;color:var(--ink-2);font-weight:600;margin-bottom:4px">' +
        esc(sec.section || sec.section_slug) + "</div>" + rows + clearRow + "</div>";
    }).join("");

    box.innerHTML = html;
    $("addonFoot").classList.remove("hide");

    [].forEach.call(box.querySelectorAll(".adopt"), function (el) {
      el.addEventListener("change", updateAddonEstimate);
    });
    updateAddonEstimate();
  }

  function chosenSlugs() {
    var box = $("addonBox");
    if (!box) { return []; }
    var out = [];
    [].forEach.call(box.querySelectorAll(".adopt"), function (el) {
      if (el.checked && el.value) { out.push(el.value); }
    });
    return out;
  }

  function updateAddonEstimate() {
    var box = $("addonBox"), est = $("addonEst");
    if (!box || !est) { return; }
    var total = 0;
    [].forEach.call(box.querySelectorAll(".adopt"), function (el) {
      if (el.checked && el.value) { total += Number(el.getAttribute("data-cents") || 0); }
    });
    est.textContent = rands(total);
  }

  function saveAddons(r) {
    var why = $("adWhy").value.trim(), go = $("adGo");
    if (!why) { $("adErr").textContent = "Give a reason \u2014 this changes a purchase price."; return; }

    go.disabled = true;
    $("adErr").textContent = "";
    $("adOk").textContent = "Saving\u2026";

    api("/staff/reservations/" + encodeURIComponent(r.uuid) + "/addons",
        { method: "POST", body: JSON.stringify({ addon_slugs: chosenSlugs(), reason: why }) })
      .then(function (res) {
        var bits = [];
        if (res.added && res.added.length) { bits.push("added " + res.added.map(label).join(", ")); }
        if (res.removed && res.removed.length) { bits.push("removed " + res.removed.map(label).join(", ")); }
        if (!bits.length) { bits.push("no change"); }
        var delta = res.total_delta_cents || 0;
        $("adOk").textContent = bits.join("; ") + ". Purchase price " +
          (delta === 0 ? "unchanged" : (delta > 0 ? "up " : "down ") + rands(Math.abs(delta))) +
          " to " + rands(res.total_cents) + ".";
        // The engine explains every rule that fired - a silently dropped add-on is
        // exactly the kind of thing sales must see rather than discover later.
        if (res.notes && res.notes.length) { $("adErr").textContent = res.notes.join(" "); }
        return load();
      })
      .then(function () { if (S.open) { openDrawer(S.open); } })
      .catch(function (e) { $("adOk").textContent = ""; $("adErr").textContent = e.message; })
      .then(function () { go.disabled = false; });
  }

  /* ---------- upgrades ----------
     THE SERVER PRICES ANYTHING THE CATALOGUE PRICES. A price box appears only for an
     option the catalogue deliberately leaves unpriced - the on-consultation ones -
     and for anything else the figure is not sent at all. Typing over a catalogue
     price is refused by Xano rather than ignored, so this panel never pretends a
     price was accepted when it was not. */
  function loadUpgrades(r) {
    var box = $("upBox");
    if (!box) { return; }
    api("/staff/reservations/" + encodeURIComponent(r.uuid) + "/options")
      .then(function (d) { if (S.open === r.uuid) { renderUpgrades(r, d); } })
      .catch(function (e) {
        if (S.open === r.uuid) {
          box.innerHTML = '<div class="err">Could not load upgrades \u2014 ' + esc(e.message) + "</div>";
        }
      });
  }

  function renderUpgrades(r, d) {
    var box = $("upBox");
    if (!box) { return; }

    var agreed = d.agreed || [];
    var groups = d.groups || [];

    var agreedHtml = agreed.length
      ? agreed.map(function (a) {
          return '<div class="otprow" style="align-items:baseline">' +
            "<span>" + esc(a.name) +
              ' <span class="muted mono">' + esc(rands(a.price_cents)) + "</span>" +
              (a.is_consultation_price ? ' <span class="tag">agreed price</span>' : "") +
            "</span>" +
            '<button class="upDrop" data-slug="' + esc(a.option_slug) + '">Remove</button>' +
          "</div>";
        }).join("")
      : '<div class="none">Nothing agreed since this buyer reserved.</div>';

    // Only what is not already on the deal. Re-adding something is a replace, and a
    // picker that offers it again invites one by accident.
    var opts = [];
    groups.forEach(function (g) {
      var avail = (g.options || []).filter(function (o) { return !o.is_agreed; });
      if (!avail.length) { return; }
      opts.push('<optgroup label="' + esc(g.name || g.slug) + '">' +
        avail.map(function (o) {
          var price = o.needs_price
            ? "price on consultation"
            : (o.price_basis === "missing" ? "no price in the catalogue" : rands(o.price_cents));
          return '<option value="' + esc(o.slug) + '"' +
            ' data-needs="' + (o.needs_price ? "1" : "") + '"' +
            ' data-missing="' + (o.price_basis === "missing" ? "1" : "") + '">' +
            esc(o.name) + " \u2014 " + esc(price) + "</option>";
        }).join("") + "</optgroup>");
    });

    /* The server withholds type-restricted upgrades when the reservation's snapshot
       records no unit type, because the writer refuses them - the two have to agree
       or sales pick something and get an error they cannot act on. Say so, rather
       than letting the list just look short. */
    var withheld = Number(d.withheld_no_unit_type || 0);
    var withheldHtml = (d.unit_type_known === false && withheld > 0)
      ? '<div class="err" style="margin-bottom:10px">' +
          "This reservation has no unit type recorded, so " + withheld +
          " upgrade" + (withheld === 1 ? "" : "s") + " that only apply to particular types " +
          "cannot be offered. Fix the unit type on the reservation first." +
        "</div>"
      : "";

    box.innerHTML =
      '<div style="margin-bottom:12px">' + agreedHtml + "</div>" +
      '<div class="muted" style="font-size:.8125rem;margin-bottom:10px">' +
        "Agreed so far: " + '<span class="mono">' + esc(rands(d.agreed_extras_total_cents || 0)) + "</span>" +
        " &middot; signed purchase price " + '<span class="mono">' + esc(rands(d.signed_total_cents)) + "</span>" +
      "</div>" +
      withheldHtml +
      (opts.length
        ? '<div style="margin-bottom:10px"><label for="upPick">Add an upgrade</label>' +
          '<select id="upPick"><option value="">Choose\u2026</option>' + opts.join("") + "</select></div>" +
          '<div id="upPriceRow" class="hide" style="margin-bottom:10px">' +
            '<label for="upPrice">Agreed price</label>' +
            '<input id="upPrice" type="text" inputmode="decimal" placeholder="e.g. 125000 for R125,000">' +
            '<div class="muted" style="font-size:.75rem;margin-top:4px">In rands. This option has no catalogue price, so what you type is what the buyer sees.</div>' +
          "</div>" +
          '<div style="margin-bottom:12px"><label for="upWhy">Reason</label>' +
          '<input id="upWhy" type="text" placeholder="What was agreed, and when"></div>' +
          '<button class="primary" id="upGo">Add upgrade</button>'
        : '<div class="none">' +
            (withheld > 0
              ? "Nothing can be offered until the unit type is recorded."
              : "Every upgrade on this development is already on the deal.") +
          "</div>") +
      '<div class="err" id="upErr" style="margin-top:10px"></div><div class="ok" id="upOk"></div>';

    var pick = $("upPick");
    if (pick) {
      pick.addEventListener("change", function () {
        var o = pick.options[pick.selectedIndex];
        var needs = o && o.getAttribute("data-needs") === "1";
        $("upPriceRow").classList[needs ? "remove" : "add"]("hide");
      });
    }
    var upGo = $("upGo");
    if (upGo) { upGo.addEventListener("click", function () { addUpgrade(r); }); }

    [].forEach.call(box.querySelectorAll(".upDrop"), function (btn) {
      btn.addEventListener("click", function () { dropUpgrade(r, btn.getAttribute("data-slug")); });
    });
  }

  function addUpgrade(r) {
    var pick = $("upPick"), why = $("upWhy").value.trim(), go = $("upGo");
    var slug = pick ? pick.value : "";
    if (!slug) { $("upErr").textContent = "Choose an upgrade first."; return; }
    if (!why) { $("upErr").textContent = "Give a reason \u2014 it goes on the record with your name."; return; }

    var o = pick.options[pick.selectedIndex];
    var needs = o.getAttribute("data-needs") === "1";
    var missing = o.getAttribute("data-missing") === "1";
    if (missing) {
      $("upErr").textContent = "That option is priced from a stored figure that is not there. Fix the catalogue rather than working around it.";
      return;
    }

    var body = { option_slug: slug, reason: why };
    if (needs) {
      var raw = ($("upPrice").value || "").replace(/[^0-9.]/g, "");
      if (!raw) { $("upErr").textContent = "This upgrade needs a price."; return; }
      var rand = Number(raw);
      if (!isFinite(rand) || rand < 0) { $("upErr").textContent = "That is not a price."; return; }
      // The field is in rands because that is how sales talk; the API is in cents
      // because that is the only way money is stored. Convert once, here.
      body.price_cents = Math.round(rand * 100);
    }

    go.disabled = true;
    $("upErr").textContent = "";
    $("upOk").textContent = "Saving\u2026";

    api("/staff/reservations/" + encodeURIComponent(r.uuid) + "/options",
        { method: "POST", body: JSON.stringify(body) })
      .then(function (res) {
        $("upOk").textContent = res.name + " added at " + rands(res.price_cents) +
          ". Extras now " + rands(res.agreed_extras_total_cents) + ".";
        loadUpgrades(r);
      })
      .catch(function (e) { $("upOk").textContent = ""; $("upErr").textContent = e.message; })
      .then(function () { go.disabled = false; });
  }

  function dropUpgrade(r, slug) {
    var why = window.prompt("Why is " + label(slug) + " coming off this order?");
    if (why === null) { return; }
    why = why.trim();
    if (!why) { $("upErr").textContent = "A reason is required to remove an upgrade."; return; }

    $("upErr").textContent = "";
    $("upOk").textContent = "Removing\u2026";
    api("/staff/reservations/" + encodeURIComponent(r.uuid) + "/options/remove",
        { method: "POST", body: JSON.stringify({ option_slug: slug, reason: why }) })
      .then(function (res) {
        $("upOk").textContent = res.name + " removed. Extras now " + rands(res.agreed_extras_total_cents) + ".";
        loadUpgrades(r);
      })
      .catch(function (e) { $("upOk").textContent = ""; $("upErr").textContent = e.message; });
  }

  /* ---------- documents ----------
     The vocabulary comes from the server, per property, so a development with its own
     document set needs nothing here. Adding a type the deal already has REPLACES it,
     and the panel says so before the save rather than after. */
  function loadDocuments(r) {
    var box = $("docBox");
    if (!box) { return; }
    api("/staff/reservations/" + encodeURIComponent(r.uuid) + "/documents")
      .then(function (d) { if (S.open === r.uuid) { renderDocuments(r, d); } })
      .catch(function (e) {
        if (S.open === r.uuid) {
          box.innerHTML = '<div class="err">Could not load documents \u2014 ' + esc(e.message) + "</div>";
        }
      });
  }

  function renderDocuments(r, d) {
    var box = $("docBox");
    if (!box) { return; }

    var live = d.documents || [];
    var types = d.document_types || [];
    var have = {};
    live.forEach(function (x) { have[x.doc_type] = x.label; });

    var listHtml = live.length
      ? live.map(function (x) {
          return '<div class="otprow" style="align-items:baseline">' +
            "<span>" + esc(x.label) +
              ' <a href="' + esc(x.url) + '" target="_blank" rel="noopener noreferrer" class="muted">open</a>' +
              '<br><span class="muted" style="font-size:.75rem">added by ' + esc(x.added_by || "\u2014") + "</span>" +
            "</span>" +
            '<button class="docDrop" data-id="' + esc(String(x.id)) + '">Remove</button>' +
          "</div>";
        }).join("")
      : '<div class="none">No documents on this deal yet.</div>';

    box.innerHTML =
      '<div style="margin-bottom:12px">' + listHtml + "</div>" +
      '<div style="margin-bottom:10px"><label for="docType">Document</label>' +
      '<select id="docType"><option value="">Choose\u2026</option>' +
        types.map(function (t) {
          return '<option value="' + esc(t.slug) + '">' + esc(t.label) +
            (have[t.slug] ? " \u2014 replaces the one already there" : "") + "</option>";
        }).join("") +
        '<option value="other">Something else\u2026</option>' +
      "</select></div>" +
      '<div id="docLabelRow" class="hide" style="margin-bottom:10px">' +
        '<label for="docLabel">Name it</label><input id="docLabel" type="text" placeholder="What the buyer will see"></div>' +
      '<div style="margin-bottom:10px"><label for="docUrl">Link</label>' +
      '<input id="docUrl" type="url" placeholder="https://\u2026"></div>' +
      '<div style="margin-bottom:12px"><label for="docWhy">Reason</label>' +
      '<input id="docWhy" type="text" placeholder="Why this is going on the portal"></div>' +
      '<button class="primary" id="docGo">Add document</button>' +
      '<div class="err" id="docErr" style="margin-top:10px"></div><div class="ok" id="docOk"></div>';

    var sel = $("docType");
    if (sel) {
      sel.addEventListener("change", function () {
        $("docLabelRow").classList[sel.value === "other" ? "remove" : "add"]("hide");
      });
    }
    var go = $("docGo");
    if (go) { go.addEventListener("click", function () { addDocument(r); }); }

    [].forEach.call(box.querySelectorAll(".docDrop"), function (btn) {
      btn.addEventListener("click", function () { dropDocument(r, btn.getAttribute("data-id")); });
    });
  }

  function addDocument(r) {
    var type = $("docType").value;
    var url = $("docUrl").value.trim();
    var why = $("docWhy").value.trim();
    var go = $("docGo");

    if (!type) { $("docErr").textContent = "Choose a document type."; return; }
    if (!url) { $("docErr").textContent = "Give a link."; return; }
    // Checked here so a typo is caught before a round trip; Xano refuses it too, and
    // the portal refuses to render it - the guard nearest the sink is the real one.
    if (url.toLowerCase().indexOf("https://") !== 0) {
      $("docErr").textContent = "The link must start with https://";
      return;
    }
    if (!why) { $("docErr").textContent = "Give a reason \u2014 it goes on the record with your name."; return; }

    var body = { doc_type: type, url: url, reason: why };
    if (type === "other") {
      var lbl = $("docLabel").value.trim();
      if (!lbl) { $("docErr").textContent = "Name the document."; return; }
      body.label = lbl;
    }

    go.disabled = true;
    $("docErr").textContent = "";
    $("docOk").textContent = "Saving\u2026";

    api("/staff/reservations/" + encodeURIComponent(r.uuid) + "/documents",
        { method: "POST", body: JSON.stringify(body) })
      .then(function (res) {
        $("docOk").textContent = res.label + (res.replaced ? " replaced the previous one." : " added.");
        loadDocuments(r);
      })
      .catch(function (e) { $("docOk").textContent = ""; $("docErr").textContent = e.message; })
      .then(function () { go.disabled = false; });
  }

  function dropDocument(r, id) {
    var why = window.prompt("Why is this document coming off the buyer's portal?");
    if (why === null) { return; }
    why = why.trim();
    if (!why) { $("docErr").textContent = "A reason is required to remove a document."; return; }

    $("docErr").textContent = "";
    $("docOk").textContent = "Removing\u2026";
    api("/staff/reservations/" + encodeURIComponent(r.uuid) + "/documents/remove",
        { method: "POST", body: JSON.stringify({ document_id: Number(id), reason: why }) })
      .then(function (res) {
        $("docOk").textContent = res.label + " removed.";
        loadDocuments(r);
      })
      .catch(function (e) { $("docOk").textContent = ""; $("docErr").textContent = e.message; });
  }

  /* ---------- deadline ---------- */
  function saveDeadline(r) {
    var clearIt = $("dlClear").checked;
    var due = $("dlDue").value;
    var why = $("dlWhy").value.trim();
    var go = $("dlGo");

    if (!why) { $("dlErr").textContent = "Give a reason \u2014 it goes on the record with your name."; return; }
    if (!clearIt && !due) { $("dlErr").textContent = "Pick a date, or tick remove."; return; }

    go.disabled = true;
    $("dlErr").textContent = "";
    $("dlOk").textContent = "Saving\u2026";

    var body = { reason: why };
    if (clearIt) { body.clear = true; }
    else { body.new_due_at = new Date(due + "T12:00:00").getTime() + ""; }

    api("/staff/reservations/" + encodeURIComponent(r.uuid) + "/deadline",
        { method: "POST", body: JSON.stringify(body) })
      .then(function (res) {
        $("dlOk").textContent = res.cleared
          ? "Deadline removed."
          : "Deadline now " + day(res.deal_stage_due_at) +
            (res.days_moved ? " (" + (res.days_moved > 0 ? "+" : "") + res.days_moved + " days)" : "") +
            (res.is_in_past ? " \u2014 note that is already in the past." : "");
        return load();
      })
      .then(function () { if (S.open) { openDrawer(S.open); } })
      .catch(function (e) { $("dlOk").textContent = ""; $("dlErr").textContent = e.message; })
      .then(function () { go.disabled = false; });
  }

  function closeDrawer() {
    S.open = null;
    $("scrim").classList.remove("open");
    $("drawer").classList.remove("open");
    $("drawer").setAttribute("aria-hidden", "true");
  }

  function moveStage(r) {
    var sub = $("mvSub").value;
    var due = $("mvDue").value;
    var why = $("mvWhy").value.trim();
    var go = $("mvGo");

    if (!why) { $("mvErr").textContent = "Give a reason — it goes on the record with your name."; return; }

    go.disabled = true;
    $("mvErr").textContent = "";
    $("mvOk").textContent = "Saving…";

    var body = { deal_stage: "finance", deal_sub_stage: sub, reason: why };
    if (due) { body.due_at_override = new Date(due + "T12:00:00").getTime() + ""; }

    api("/staff/reservations/" + encodeURIComponent(r.uuid) + "/stage",
        { method: "POST", body: JSON.stringify(body) })
      .then(function (res) {
        $("mvOk").textContent = "Moved to " + label(res.deal_sub_stage) +
          (res.deal_stage_due_at ? ", due " + day(res.deal_stage_due_at) : "") + ".";
        return load();
      })
      .then(function () { if (S.open) { openDrawer(S.open); } })
      .catch(function (e) { $("mvOk").textContent = ""; $("mvErr").textContent = e.message; })
      .then(function () { go.disabled = false; });
  }

  /* ---------- csv ---------- */
  function csv() {
    if (!S.data || !S.data.items.length) { return; }
    var cols = ["uuid", "reference", "status", "deal_stage", "deal_sub_stage", "deal_stage_due_at",
      "property_slug", "unit_name", "first_name", "last_name", "email", "phone", "payer_route",
      "reservation_fee_cents", "total_cents", "purchase_deposit_cents", "purchase_deposit_paid_cents",
      "addon_count", "payment_status", "pf_payment_id", "confirmed_at", "admin_notes"];
    var lines = [cols.join(",")];
    S.data.items.forEach(function (r) {
      lines.push(cols.map(function (c) {
        var v = r[c];
        if (v === null || v === undefined) { return ""; }
        v = String(v);
        return /[",\n]/.test(v) ? '"' + v.replace(/"/g, '""') + '"' : v;
      }).join(","));
    });
    var a = document.createElement("a");
    a.href = URL.createObjectURL(new Blob([lines.join("\n")], { type: "text/csv;charset=utf-8" }));
    a.download = "heartland-pipeline-" + new Date().toISOString().slice(0, 10) + ".csv";
    document.body.appendChild(a); a.click(); document.body.removeChild(a);
    URL.revokeObjectURL(a.href);
  }

  /* ---------- session ---------- */
  function showApp() {
    $("login").classList.add("hide");
    $("app").classList.remove("hide");
    load();
  }
  function signOut(msg) {
    clearSession();
    S.data = null;
    closeDrawer();
    $("app").classList.add("hide");
    $("login").classList.remove("hide");
    $("loginErr").textContent = msg || "";
  }

  $("signin").addEventListener("click", function () {
    var e = $("email").value.trim(), p = $("pw").value;
    if (!e || !p) { $("loginErr").textContent = "Email and password, please."; return; }
    $("loginErr").textContent = "Checking…";
    api("/staff/login", { auth: false, method: "POST", body: JSON.stringify({ email: e, password: p }) })
      .then(function (d) {
        setSession(d.authToken, d.staff);
        $("pw").value = "";
        $("loginErr").textContent = "";
        showApp();
      })
      .catch(function (err) { $("loginErr").textContent = err.message; });
  });
  $("pw").addEventListener("keydown", function (ev) { if (ev.key === "Enter") { $("signin").click(); } });

  $("signout").addEventListener("click", function () { signOut(""); });
  $("refresh").addEventListener("click", load);
  $("csv").addEventListener("click", csv);
  $("scrim").addEventListener("click", closeDrawer);
  document.addEventListener("keydown", function (e) { if (e.key === "Escape") { closeDrawer(); } });

  function tab(which) {
    S.tab = which;
    $("tabToday").setAttribute("aria-selected", which === "today");
    $("tabPipe").setAttribute("aria-selected", which === "pipe");
    $("viewToday").classList.toggle("hide", which !== "today");
    $("viewPipe").classList.toggle("hide", which !== "pipe");
  }
  $("tabToday").addEventListener("click", function () { tab("today"); });
  $("tabPipe").addEventListener("click", function () { tab("pipe"); });

  var t = null;
  $("q").addEventListener("input", function () { clearTimeout(t); t = setTimeout(load, 300); });
  ["fstatus", "fstage", "fprop"].forEach(function (id) { $(id).addEventListener("change", load); });

  if (token()) { S.staff = savedStaff(); showApp(); }
})();
