#!/usr/bin/env python3
"""
Build heartland-console.js from heartland-sales-console.html.

WHY THIS EXISTS. The console outgrew Webflow's 50,000-character Code Embed cap
(48,130 of it in one embed, 1,870 to spare), and splitting a <script> across two
embeds is not a trick that keeps working. It now ships the same way the reserve
flow does: one file in GitHub, served by jsDelivr, with a fixed four-line embed on
the Webflow page that never changes again.

The HTML file stays the source of truth because it is the only form you can open in
a browser and click through without a build. This script is the whole build: it
lifts the <template> into a JS string and the <script> body out from around it.
Nothing is rewritten by hand, so the two cannot drift.
"""
import json, sys, hashlib, os

# Paths are relative to THIS FILE, not to the shell's working directory, so the build
# gives the same answer whether you run it from the repo root or from src/.
HERE = os.path.dirname(os.path.abspath(__file__))
SRC  = os.path.join(HERE, 'heartland-sales-console.html')
OUT  = os.path.join(HERE, '..', 'heartland-console.js')

lines = open(SRC, encoding='utf-8').read().split('\n')

def idx(pred, what):
    for i, l in enumerate(lines):
        if pred(l):
            return i
    sys.exit('build: could not find ' + what)

tpl_open  = idx(lambda l: l.strip().startswith('<template id="hl-console-tpl"'), 'the template open tag')
tpl_close = idx(lambda l: l.strip() == '</template>', 'the template close tag')
scr_open  = idx(lambda l: l.strip() == '<script>', 'the script open tag')
scr_close = max(i for i, l in enumerate(lines) if l.strip() == '</script>')

if scr_open != tpl_close + 1:
    sys.exit('build: the script no longer follows the template directly - check the file')

tpl_lines = lines[tpl_open + 1:tpl_close]
body      = lines[scr_open + 1:scr_close]

# The template is emitted as json-encoded lines rather than a template literal.
# A backslash, a backtick or a ${ appearing in the markup later would silently
# corrupt a literal; json.dumps cannot be surprised by any of them.
tpl_js = ',\n    '.join(json.dumps(l) for l in tpl_lines)

# The bootstrap in the HTML reads the <template> out of the page. There is no page
# here, so those three lines are replaced - and ONLY those three, matched exactly,
# so a change to them fails the build rather than being quietly ignored.
OLD_BOOT = [
    '  var host = document.getElementById("hl-console-host");',
    '  var root = host.attachShadow({ mode: "open" });',
    '  root.appendChild(document.getElementById("hl-console-tpl").content.cloneNode(true));',
]
for i in range(len(body) - 2):
    if body[i:i + 3] == OLD_BOOT:
        boot_at = i
        break
else:
    sys.exit('build: the shadow-root bootstrap has changed - update OLD_BOOT')

NEW_BOOT = [
    '  /* Served from a file, not from a page, so the markup arrives as a string and is',
    '     parsed into a template here. Everything downstream is unchanged: root is still',
    '     a ShadowRoot and $ still calls getElementById on it. */',
    '  var host = document.getElementById("hl-console-host");',
    '  if (!host) {',
    '    /* Loaded on a page that is not the console. Say so once and stop - throwing',
    '       here would put a red error in the console of an ordinary marketing page. */',
    '    console.warn("[hl-console] no #hl-console-host on this page - nothing to render.");',
    '    return;',
    '  }',
    '  if (host.shadowRoot) {',
    '    console.warn("[hl-console] already initialised - the script is on this page twice.");',
    '    return;',
    '  }',
    '  var root = host.attachShadow({ mode: "open" });',
    '  var tplEl = document.createElement("template");',
    '  tplEl.innerHTML = TPL;',
    '  root.appendChild(tplEl.content.cloneNode(true));',
]

body = body[:boot_at] + NEW_BOOT + body[boot_at + 3:]

header = '''/* Heartland - sales console.
   Built from heartland-sales-console.html by build_console.py. DO NOT EDIT THIS FILE.
   Edit the HTML, run the build, push. The HTML is the version you can open in a
   browser and click through; this is the version Webflow loads.

   On the page, all that is needed is:

     <style>html,body{margin:0;padding:0;background:#f9f9f7}
     @media(prefers-color-scheme:dark){html,body{background:#0d0d0d}}</style>
     <div id="hl-console-host"></div>
     <script src="https://cdn.jsdelivr.net/gh/daniellun-tov/heartland-scripts@main/heartland-console.js" defer><\/script>

   Everything else - every style, every element, every handler - is in here, sealed
   inside a shadow root so the marketing site's stylesheet cannot reach it. */
'''

# The body already opens its own IIFE and declares 'use strict'. TPL is injected
# just after that, rather than wrapped in a second IIFE - one opener, one closer.
for i, l in enumerate(body):
    if l.strip() == "'use strict';":
        strict_at = i
        break
else:
    sys.exit("build: no 'use strict' at the top of the script body")

tpl_block = ['', '  var TPL = [', '    ' + tpl_js, '  ].join("\\n");']
body = body[:strict_at + 1] + tpl_block + body[strict_at + 1:]

out = header + '\n'.join(body) + '\n' 

open(OUT, 'w', encoding='utf-8').write(out)
print('wrote %s  %d chars  %d lines  sha256 %s'
      % (os.path.normpath(OUT), len(out), out.count('\n') + 1,
         hashlib.sha256(out.encode('utf-8')).hexdigest()[:16]))
